name: Network

on: [push]
  #workflow_call:
    inputs:
      ENV:
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      CDK_DEFAULT_REGION:
        required: true
      CDK_DEFAULT_ACCOUNT:
        required: true
env:
  ENV: ${{ inputs.ENV }}
  CDK_DEFAULT_REGION: ${{ secrets.CDK_DEFAULT_REGION }}
  CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
  AWS_REGION: ${{ secrets.CDK_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  NODE_VERSION: '16'

jobs:
  deploy-cognito:
    name: Build and Deploy Network
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Deploy Network
        run: |
          cd packages/infra/network
          yarn install
          npx aws-cdk synth
          npx aws-cdk deploy --require-approval never